/// Dart API of the messenger_core Rust engine (generated by
/// flutter_rust_bridge from `rust/bridge`).
///
/// Call `await RustLib.init()` once before using [MessengerApi].
library;

export 'src/rust/api/messenger.dart';
export 'src/rust/api/types.dart';
export 'src/rust/frb_generated.dart' show RustLib;
