// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/messenger.dart';
import 'api/types.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1182193373;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'messenger_bridge',
        ioDirectory: '../rust/bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  int crateApiMessengerMessengerApiActiveEventStreams({
    required MessengerApi that,
  });

  Future<List<RoomSummary>> crateApiMessengerMessengerApiCachedRooms({
    required MessengerApi that,
  });

  Future<MessengerApi> crateApiMessengerMessengerApiCreate({
    required String homeserverUrl,
    required String dataDir,
    required SecretStorage secretStorage,
  });

  String? crateApiMessengerMessengerApiCurrentUser({
    required MessengerApi that,
  });

  Stream<CoreEvent> crateApiMessengerMessengerApiEvents({
    required MessengerApi that,
  });

  String crateApiMessengerMessengerApiHomeserver({required MessengerApi that});

  Future<List<Message>> crateApiMessengerMessengerApiLoadMessages({
    required MessengerApi that,
    required String roomId,
    required int limit,
  });

  Future<void> crateApiMessengerMessengerApiLogin({
    required MessengerApi that,
    required String username,
    required String password,
  });

  Future<LogoutOutcome> crateApiMessengerMessengerApiLogout({
    required MessengerApi that,
  });

  Future<List<RoomSummary>> crateApiMessengerMessengerApiRefreshRooms({
    required MessengerApi that,
  });

  Future<RestoreOutcome> crateApiMessengerMessengerApiRestoreSession({
    required MessengerApi that,
  });

  Future<SentMessage> crateApiMessengerMessengerApiSendTextMessage({
    required MessengerApi that,
    required String roomId,
    required String body,
  });

  Future<void> crateApiMessengerMessengerApiStartSync({
    required MessengerApi that,
  });

  Future<void> crateApiMessengerMessengerApiStopSync({
    required MessengerApi that,
  });

  SyncState crateApiMessengerMessengerApiSyncState({
    required MessengerApi that,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MessengerApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MessengerApi;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MessengerApiPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  int crateApiMessengerMessengerApiActiveEventStreams({
    required MessengerApi that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMessengerMessengerApiActiveEventStreamsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiActiveEventStreamsConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_active_event_streams",
        argNames: ["that"],
      );

  @override
  Future<List<RoomSummary>> crateApiMessengerMessengerApiCachedRooms({
    required MessengerApi that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_room_summary,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiMessengerMessengerApiCachedRoomsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiCachedRoomsConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_cached_rooms",
        argNames: ["that"],
      );

  @override
  Future<MessengerApi> crateApiMessengerMessengerApiCreate({
    required String homeserverUrl,
    required String dataDir,
    required SecretStorage secretStorage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(homeserverUrl, serializer);
          sse_encode_String(dataDir, serializer);
          sse_encode_secret_storage(secretStorage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiMessengerMessengerApiCreateConstMeta,
        argValues: [homeserverUrl, dataDir, secretStorage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiCreateConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_create",
        argNames: ["homeserverUrl", "dataDir", "secretStorage"],
      );

  @override
  String? crateApiMessengerMessengerApiCurrentUser({
    required MessengerApi that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMessengerMessengerApiCurrentUserConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiCurrentUserConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_current_user",
        argNames: ["that"],
      );

  @override
  Stream<CoreEvent> crateApiMessengerMessengerApiEvents({
    required MessengerApi that,
  }) {
    final sink = RustStreamSink<CoreEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
              that,
              serializer,
            );
            sse_encode_StreamSink_core_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 5,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiMessengerMessengerApiEventsConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiEventsConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_events",
        argNames: ["that", "sink"],
      );

  @override
  String crateApiMessengerMessengerApiHomeserver({required MessengerApi that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMessengerMessengerApiHomeserverConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiHomeserverConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_homeserver",
        argNames: ["that"],
      );

  @override
  Future<List<Message>> crateApiMessengerMessengerApiLoadMessages({
    required MessengerApi that,
    required String roomId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          sse_encode_u_16(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiMessengerMessengerApiLoadMessagesConstMeta,
        argValues: [that, roomId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiLoadMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_load_messages",
        argNames: ["that", "roomId", "limit"],
      );

  @override
  Future<void> crateApiMessengerMessengerApiLogin({
    required MessengerApi that,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiMessengerMessengerApiLoginConstMeta,
        argValues: [that, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiLoginConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_login",
        argNames: ["that", "username", "password"],
      );

  @override
  Future<LogoutOutcome> crateApiMessengerMessengerApiLogout({
    required MessengerApi that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_logout_outcome,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiMessengerMessengerApiLogoutConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiLogoutConstMeta =>
      const TaskConstMeta(debugName: "MessengerApi_logout", argNames: ["that"]);

  @override
  Future<List<RoomSummary>> crateApiMessengerMessengerApiRefreshRooms({
    required MessengerApi that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_room_summary,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiMessengerMessengerApiRefreshRoomsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiRefreshRoomsConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_refresh_rooms",
        argNames: ["that"],
      );

  @override
  Future<RestoreOutcome> crateApiMessengerMessengerApiRestoreSession({
    required MessengerApi that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_restore_outcome,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiMessengerMessengerApiRestoreSessionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiRestoreSessionConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_restore_session",
        argNames: ["that"],
      );

  @override
  Future<SentMessage> crateApiMessengerMessengerApiSendTextMessage({
    required MessengerApi that,
    required String roomId,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          sse_encode_String(roomId, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sent_message,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiMessengerMessengerApiSendTextMessageConstMeta,
        argValues: [that, roomId, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiSendTextMessageConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_send_text_message",
        argNames: ["that", "roomId", "body"],
      );

  @override
  Future<void> crateApiMessengerMessengerApiStartSync({
    required MessengerApi that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiMessengerMessengerApiStartSyncConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiStartSyncConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_start_sync",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiMessengerMessengerApiStopSync({
    required MessengerApi that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiMessengerMessengerApiStopSyncConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiStopSyncConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_stop_sync",
        argNames: ["that"],
      );

  @override
  SyncState crateApiMessengerMessengerApiSyncState({
    required MessengerApi that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMessengerMessengerApiSyncStateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerMessengerApiSyncStateConstMeta =>
      const TaskConstMeta(
        debugName: "MessengerApi_sync_state",
        argNames: ["that"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MessengerApi => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MessengerApi => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  MessengerApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessengerApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MessengerApi
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessengerApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MessengerApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessengerApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MessengerApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessengerApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<CoreEvent> dco_decode_StreamSink_core_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApiError dco_decode_api_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ApiError_InvalidHomeserver(reason: dco_decode_String(raw[1]));
      case 1:
        return ApiError_ClientInitialization();
      case 2:
        return ApiError_AlreadyAuthenticated();
      case 3:
        return ApiError_InvalidCredentials();
      case 4:
        return ApiError_HomeserverUnreachable();
      case 5:
        return ApiError_AuthenticationFailed();
      case 6:
        return ApiError_InvalidSession();
      case 7:
        return ApiError_NotAuthenticated();
      case 8:
        return ApiError_SessionRevoked();
      case 9:
        return ApiError_SyncFailed();
      case 10:
        return ApiError_AlreadySyncing();
      case 11:
        return ApiError_RoomNotFound();
      case 12:
        return ApiError_NotJoined();
      case 13:
        return ApiError_InvalidMessage();
      case 14:
        return ApiError_MessageLoadFailed();
      case 15:
        return ApiError_MessageSendFailed();
      case 16:
        return ApiError_Storage();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Message dco_decode_box_autoadd_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_message(raw);
  }

  @protected
  CoreEvent dco_decode_core_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CoreEvent_MessageReceived(
          roomId: dco_decode_String(raw[1]),
          message: dco_decode_box_autoadd_message(raw[2]),
        );
      case 1:
        return CoreEvent_RoomsChanged();
      case 2:
        return CoreEvent_TimelineGap(roomId: dco_decode_String(raw[1]));
      case 3:
        return CoreEvent_SyncStateChanged(state: dco_decode_sync_state(raw[1]));
      case 4:
        return CoreEvent_SessionRevoked();
      case 5:
        return CoreEvent_EventsLost(count: dco_decode_i_64(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Message> dco_decode_list_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RoomSummary> dco_decode_list_room_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_room_summary).toList();
  }

  @protected
  LogoutOutcome dco_decode_logout_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LogoutOutcome.values[raw as int];
  }

  @protected
  Message dco_decode_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Message(
      id: dco_decode_String(arr[0]),
      sender: dco_decode_String(arr[1]),
      body: dco_decode_String(arr[2]),
      timestampMs: dco_decode_i_64(arr[3]),
      isOwn: dco_decode_bool(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RestoreOutcome dco_decode_restore_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RestoreOutcome.values[raw as int];
  }

  @protected
  RoomSummary dco_decode_room_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RoomSummary(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      isDirect: dco_decode_bool(arr[2]),
    );
  }

  @protected
  SecretStorage dco_decode_secret_storage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SecretStorage.values[raw as int];
  }

  @protected
  SentMessage dco_decode_sent_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return SentMessage(eventId: dco_decode_String(arr[0]));
  }

  @protected
  SyncState dco_decode_sync_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncState.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  MessengerApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MessengerApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MessengerApi
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MessengerApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MessengerApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MessengerApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MessengerApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MessengerApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<CoreEvent> sse_decode_StreamSink_core_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApiError sse_decode_api_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_reason = sse_decode_String(deserializer);
        return ApiError_InvalidHomeserver(reason: var_reason);
      case 1:
        return ApiError_ClientInitialization();
      case 2:
        return ApiError_AlreadyAuthenticated();
      case 3:
        return ApiError_InvalidCredentials();
      case 4:
        return ApiError_HomeserverUnreachable();
      case 5:
        return ApiError_AuthenticationFailed();
      case 6:
        return ApiError_InvalidSession();
      case 7:
        return ApiError_NotAuthenticated();
      case 8:
        return ApiError_SessionRevoked();
      case 9:
        return ApiError_SyncFailed();
      case 10:
        return ApiError_AlreadySyncing();
      case 11:
        return ApiError_RoomNotFound();
      case 12:
        return ApiError_NotJoined();
      case 13:
        return ApiError_InvalidMessage();
      case 14:
        return ApiError_MessageLoadFailed();
      case 15:
        return ApiError_MessageSendFailed();
      case 16:
        return ApiError_Storage();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Message sse_decode_box_autoadd_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_message(deserializer));
  }

  @protected
  CoreEvent sse_decode_core_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_roomId = sse_decode_String(deserializer);
        var var_message = sse_decode_box_autoadd_message(deserializer);
        return CoreEvent_MessageReceived(
          roomId: var_roomId,
          message: var_message,
        );
      case 1:
        return CoreEvent_RoomsChanged();
      case 2:
        var var_roomId = sse_decode_String(deserializer);
        return CoreEvent_TimelineGap(roomId: var_roomId);
      case 3:
        var var_state = sse_decode_sync_state(deserializer);
        return CoreEvent_SyncStateChanged(state: var_state);
      case 4:
        return CoreEvent_SessionRevoked();
      case 5:
        var var_count = sse_decode_i_64(deserializer);
        return CoreEvent_EventsLost(count: var_count);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Message> sse_decode_list_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Message>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RoomSummary> sse_decode_list_room_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RoomSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_room_summary(deserializer));
    }
    return ans_;
  }

  @protected
  LogoutOutcome sse_decode_logout_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LogoutOutcome.values[inner];
  }

  @protected
  Message sse_decode_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_sender = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_timestampMs = sse_decode_i_64(deserializer);
    var var_isOwn = sse_decode_bool(deserializer);
    return Message(
      id: var_id,
      sender: var_sender,
      body: var_body,
      timestampMs: var_timestampMs,
      isOwn: var_isOwn,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RestoreOutcome sse_decode_restore_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RestoreOutcome.values[inner];
  }

  @protected
  RoomSummary sse_decode_room_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_isDirect = sse_decode_bool(deserializer);
    return RoomSummary(
      id: var_id,
      displayName: var_displayName,
      isDirect: var_isDirect,
    );
  }

  @protected
  SecretStorage sse_decode_secret_storage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SecretStorage.values[inner];
  }

  @protected
  SentMessage sse_decode_sent_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventId = sse_decode_String(deserializer);
    return SentMessage(eventId: var_eventId);
  }

  @protected
  SyncState sse_decode_sync_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SyncState.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    MessengerApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MessengerApiImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    MessengerApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MessengerApiImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    MessengerApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MessengerApiImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMessengerApi(
    MessengerApi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MessengerApiImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_core_event_Sse(
    RustStreamSink<CoreEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_core_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_api_error(ApiError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ApiError_InvalidHomeserver(reason: final reason):
        sse_encode_i_32(0, serializer);
        sse_encode_String(reason, serializer);
      case ApiError_ClientInitialization():
        sse_encode_i_32(1, serializer);
      case ApiError_AlreadyAuthenticated():
        sse_encode_i_32(2, serializer);
      case ApiError_InvalidCredentials():
        sse_encode_i_32(3, serializer);
      case ApiError_HomeserverUnreachable():
        sse_encode_i_32(4, serializer);
      case ApiError_AuthenticationFailed():
        sse_encode_i_32(5, serializer);
      case ApiError_InvalidSession():
        sse_encode_i_32(6, serializer);
      case ApiError_NotAuthenticated():
        sse_encode_i_32(7, serializer);
      case ApiError_SessionRevoked():
        sse_encode_i_32(8, serializer);
      case ApiError_SyncFailed():
        sse_encode_i_32(9, serializer);
      case ApiError_AlreadySyncing():
        sse_encode_i_32(10, serializer);
      case ApiError_RoomNotFound():
        sse_encode_i_32(11, serializer);
      case ApiError_NotJoined():
        sse_encode_i_32(12, serializer);
      case ApiError_InvalidMessage():
        sse_encode_i_32(13, serializer);
      case ApiError_MessageLoadFailed():
        sse_encode_i_32(14, serializer);
      case ApiError_MessageSendFailed():
        sse_encode_i_32(15, serializer);
      case ApiError_Storage():
        sse_encode_i_32(16, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_message(Message self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_message(self, serializer);
  }

  @protected
  void sse_encode_core_event(CoreEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CoreEvent_MessageReceived(
        roomId: final roomId,
        message: final message,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(roomId, serializer);
        sse_encode_box_autoadd_message(message, serializer);
      case CoreEvent_RoomsChanged():
        sse_encode_i_32(1, serializer);
      case CoreEvent_TimelineGap(roomId: final roomId):
        sse_encode_i_32(2, serializer);
        sse_encode_String(roomId, serializer);
      case CoreEvent_SyncStateChanged(state: final state):
        sse_encode_i_32(3, serializer);
        sse_encode_sync_state(state, serializer);
      case CoreEvent_SessionRevoked():
        sse_encode_i_32(4, serializer);
      case CoreEvent_EventsLost(count: final count):
        sse_encode_i_32(5, serializer);
        sse_encode_i_64(count, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_message(List<Message> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_room_summary(
    List<RoomSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_room_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_logout_outcome(LogoutOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_message(Message self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_i_64(self.timestampMs, serializer);
    sse_encode_bool(self.isOwn, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_restore_outcome(
    RestoreOutcome self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_room_summary(RoomSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_bool(self.isDirect, serializer);
  }

  @protected
  void sse_encode_secret_storage(SecretStorage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sent_message(SentMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.eventId, serializer);
  }

  @protected
  void sse_encode_sync_state(SyncState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class MessengerApiImpl extends RustOpaque implements MessengerApi {
  // Not to be used by end users
  MessengerApiImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MessengerApiImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MessengerApi,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MessengerApi,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_MessengerApiPtr,
  );

  /// Number of event streams still forwarding events (diagnostics).
  int activeEventStreams() => RustLib.instance.api
      .crateApiMessengerMessengerApiActiveEventStreams(that: this);

  /// Joined rooms from the local store, without network.
  Future<List<RoomSummary>> cachedRooms() =>
      RustLib.instance.api.crateApiMessengerMessengerApiCachedRooms(that: this);

  /// Matrix ID of the authenticated user, or `None`.
  String? currentUser() =>
      RustLib.instance.api.crateApiMessengerMessengerApiCurrentUser(that: this);

  /// Stream of the events emitted from now on. Independent of the sync:
  /// subscribing does not start it.
  ///
  /// Each stream is fed by a small task that ends when the client is
  /// disposed (the stream then closes) or once events can no longer be
  /// delivered after the Dart subscription was cancelled. With
  /// flutter_rust_bridge, a cancellation only takes effect when the next
  /// event reaches Dart (`cancel()` completes then) and the task ends on
  /// the following one: don't await `cancel()` when no event may follow;
  /// `dispose()` closes every stream immediately.
  Stream<CoreEvent> events() =>
      RustLib.instance.api.crateApiMessengerMessengerApiEvents(that: this);

  /// Homeserver URL the client is configured for.
  String homeserver() =>
      RustLib.instance.api.crateApiMessengerMessengerApiHomeserver(that: this);

  /// Latest text messages of a joined room from the homeserver, oldest
  /// first, at most `limit` (capped at 100).
  Future<List<Message>> loadMessages({
    required String roomId,
    required int limit,
  }) => RustLib.instance.api.crateApiMessengerMessengerApiLoadMessages(
    that: this,
    roomId: roomId,
    limit: limit,
  );

  /// Logs in with a username (or full Matrix ID) and password. The
  /// password is only used for this request and never stored.
  Future<void> login({required String username, required String password}) =>
      RustLib.instance.api.crateApiMessengerMessengerApiLogin(
        that: this,
        username: username,
        password: password,
      );

  /// Logs out (stopping the sync first); always removes the local session.
  Future<LogoutOutcome> logout() =>
      RustLib.instance.api.crateApiMessengerMessengerApiLogout(that: this);

  /// Syncs once with the homeserver (unless the continuous sync runs) and
  /// returns the joined rooms.
  Future<List<RoomSummary>> refreshRooms() => RustLib.instance.api
      .crateApiMessengerMessengerApiRefreshRooms(that: this);

  /// Restores the session persisted by a previous login.
  Future<RestoreOutcome> restoreSession() => RustLib.instance.api
      .crateApiMessengerMessengerApiRestoreSession(that: this);

  /// Sends a plain text message; returns its event ID.
  Future<SentMessage> sendTextMessage({
    required String roomId,
    required String body,
  }) => RustLib.instance.api.crateApiMessengerMessengerApiSendTextMessage(
    that: this,
    roomId: roomId,
    body: body,
  );

  /// Starts the continuous sync. Subscribe to `events` first to receive
  /// everything it emits.
  Future<void> startSync() =>
      RustLib.instance.api.crateApiMessengerMessengerApiStartSync(that: this);

  /// Stops the continuous sync; does nothing if it is not running.
  Future<void> stopSync() =>
      RustLib.instance.api.crateApiMessengerMessengerApiStopSync(that: this);

  /// Current state of the continuous sync.
  SyncState syncState() =>
      RustLib.instance.api.crateApiMessengerMessengerApiSyncState(that: this);
}
