// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `convert`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActiveStream`, `DropInRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref_mut`, `deref`, `drop`, `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MessengerApi>>
abstract class MessengerApi implements RustOpaqueInterface {
  /// Number of event streams still forwarding events (diagnostics).
  int activeEventStreams();

  /// Joined rooms from the local store, without network.
  Future<List<RoomSummary>> cachedRooms();

  /// Creates the client for `homeserver_url` (e.g. `https://matrix.org`),
  /// storing its data in `data_dir` (an app data directory chosen by the
  /// caller) and its session secrets in `secret_storage`. Does not restore
  /// any session: call `restore_session`.
  static Future<MessengerApi> create({
    required String homeserverUrl,
    required String dataDir,
    required SecretStorage secretStorage,
  }) => RustLib.instance.api.crateApiMessengerMessengerApiCreate(
    homeserverUrl: homeserverUrl,
    dataDir: dataDir,
    secretStorage: secretStorage,
  );

  /// Matrix ID of the authenticated user, or `None`.
  String? currentUser();

  /// Stream of the events emitted from now on. Independent of the sync:
  /// subscribing does not start it.
  ///
  /// Each stream is fed by a small task that ends when the client is
  /// disposed (the stream then closes) or once events can no longer be
  /// delivered after the Dart subscription was cancelled. With
  /// flutter_rust_bridge, a cancellation only takes effect when the next
  /// event reaches Dart (`cancel()` completes then) and the task ends on
  /// the following one: don't await `cancel()` when no event may follow;
  /// `dispose()` closes every stream immediately.
  Stream<CoreEvent> events();

  /// Homeserver URL the client is configured for.
  String homeserver();

  /// Latest text messages of a joined room from the homeserver, oldest
  /// first, at most `limit` (capped at 100).
  Future<List<Message>> loadMessages({
    required String roomId,
    required int limit,
  });

  /// Logs in with a username (or full Matrix ID) and password. The
  /// password is only used for this request and never stored.
  Future<void> login({required String username, required String password});

  /// Logs out (stopping the sync first); always removes the local session.
  Future<LogoutOutcome> logout();

  /// Syncs once with the homeserver (unless the continuous sync runs) and
  /// returns the joined rooms.
  Future<List<RoomSummary>> refreshRooms();

  /// Restores the session persisted by a previous login.
  Future<RestoreOutcome> restoreSession();

  /// Sends a plain text message; returns its event ID.
  Future<SentMessage> sendTextMessage({
    required String roomId,
    required String body,
  });

  /// Starts the continuous sync. Subscribe to `events` first to receive
  /// everything it emits.
  Future<void> startSync();

  /// Stops the continuous sync; does nothing if it is not running.
  Future<void> stopSync();

  /// Current state of the continuous sync.
  SyncState syncState();
}
