// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `saturating_i64`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

@freezed
sealed class ApiError with _$ApiError implements FrbException {
  const ApiError._();

  const factory ApiError.invalidHomeserver({required String reason}) =
      ApiError_InvalidHomeserver;
  const factory ApiError.clientInitialization() = ApiError_ClientInitialization;
  const factory ApiError.alreadyAuthenticated() = ApiError_AlreadyAuthenticated;
  const factory ApiError.invalidCredentials() = ApiError_InvalidCredentials;
  const factory ApiError.homeserverUnreachable() =
      ApiError_HomeserverUnreachable;
  const factory ApiError.authenticationFailed() = ApiError_AuthenticationFailed;
  const factory ApiError.invalidSession() = ApiError_InvalidSession;
  const factory ApiError.notAuthenticated() = ApiError_NotAuthenticated;
  const factory ApiError.sessionRevoked() = ApiError_SessionRevoked;
  const factory ApiError.syncFailed() = ApiError_SyncFailed;
  const factory ApiError.alreadySyncing() = ApiError_AlreadySyncing;
  const factory ApiError.roomNotFound() = ApiError_RoomNotFound;
  const factory ApiError.notJoined() = ApiError_NotJoined;
  const factory ApiError.invalidMessage() = ApiError_InvalidMessage;
  const factory ApiError.messageLoadFailed() = ApiError_MessageLoadFailed;
  const factory ApiError.messageSendFailed() = ApiError_MessageSendFailed;
  const factory ApiError.storage() = ApiError_Storage;
}

@freezed
sealed class CoreEvent with _$CoreEvent {
  const CoreEvent._();

  /// A new text message arrived (once per event ID).
  const factory CoreEvent.messageReceived({
    required String roomId,
    required Message message,
  }) = CoreEvent_MessageReceived;

  /// The joined rooms changed: call `cached_rooms`.
  const factory CoreEvent.roomsChanged() = CoreEvent_RoomsChanged;

  /// Messages of this room were skipped: reload them with `load_messages`.
  const factory CoreEvent.timelineGap({required String roomId}) =
      CoreEvent_TimelineGap;

  /// The sync state changed.
  const factory CoreEvent.syncStateChanged({required SyncState state}) =
      CoreEvent_SyncStateChanged;

  /// The access token was rejected: the session was removed, log in again.
  const factory CoreEvent.sessionRevoked() = CoreEvent_SessionRevoked;

  /// The stream fell behind and `count` events were dropped: reload state.
  const factory CoreEvent.eventsLost({required PlatformInt64 count}) =
      CoreEvent_EventsLost;
}

/// Result of `logout`.
enum LogoutOutcome {
  /// Revoked on the homeserver and removed locally.
  complete,

  /// Removed locally only: the homeserver could not be reached.
  localOnly,
}

/// A text message.
class Message {
  /// Matrix event ID.
  final String id;

  /// Matrix user ID of the sender.
  final String sender;

  /// Plain text body.
  final String body;

  /// Server timestamp, in milliseconds since the Unix epoch.
  final PlatformInt64 timestampMs;

  /// Whether the authenticated user sent this message.
  final bool isOwn;

  const Message({
    required this.id,
    required this.sender,
    required this.body,
    required this.timestampMs,
    required this.isOwn,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sender.hashCode ^
      body.hashCode ^
      timestampMs.hashCode ^
      isOwn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sender == other.sender &&
          body == other.body &&
          timestampMs == other.timestampMs &&
          isOwn == other.isOwn;
}

/// Result of `restore_session`.
enum RestoreOutcome {
  /// No persisted session (e.g. first run): log in.
  noSession,

  /// The persisted session was restored.
  restored,
}

/// A joined conversation.
class RoomSummary {
  /// Matrix room ID, e.g. `!abc:matrix.org`.
  final String id;

  /// Name to show, computed by the Matrix SDK.
  final String displayName;

  /// Whether the room is a direct chat.
  final bool isDirect;

  const RoomSummary({
    required this.id,
    required this.displayName,
    required this.isDirect,
  });

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode ^ isDirect.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          isDirect == other.isDirect;
}

/// Where session secrets (access token, store key) are kept.
enum SecretStorage {
  /// The OS credential store (Keychain, Credential Manager, Secret
  /// Service). Use this in the app.
  system,

  /// Process memory only: for automated tests, which must not touch the
  /// user's credential store.
  inMemory,
}

/// Confirmation of a sent message.
class SentMessage {
  /// Matrix event ID assigned by the homeserver.
  final String eventId;

  const SentMessage({required this.eventId});

  @override
  int get hashCode => eventId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SentMessage &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId;
}

/// State of the continuous sync.
enum SyncState { stopped, starting, running, recovering }
