//! Flutter Rust Bridge adapter for `messenger_core`.
//!
//! Only `api` is scanned by the code generator. It adapts the core's API to
//! FFI-friendly types and holds no business logic of its own.

pub mod api;
// Generated by flutter_rust_bridge_codegen: never edited nor reformatted.
#[rustfmt::skip]
mod frb_generated;
